In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print("a:", a)

a: [1 2 3]


In [4]:
a = np.array([1, 2, 3], dtype=np.int32)
print("a with dtype:", a)

a with dtype: [1 2 3]


In [5]:
b = np.array([[1.5, 2.3], [3.1, 4.7]])
print("b:", b)

b: [[1.5 2.3]
 [3.1 4.7]]


In [6]:
print("b.ndim (number of dimensions):", b.ndim)
print("b.shape (dimensions):", b.shape)
print("b.size (total elements):", b.size)
print("b.dtype (data type):", b.dtype)

b.ndim (number of dimensions): 2
b.shape (dimensions): (2, 2)
b.size (total elements): 4
b.dtype (data type): float64


In [7]:
data = np.array([1, 2, 3, 4, 5, 6])
print("data[0]:", data[0])
print("data[1:4]:", data[1:4])
print("data[:2]:", data[:2])
print("data[::2]:", data[::2])

data[0]: 1
data[1:4]: [2 3 4]
data[:2]: [1 2]
data[::2]: [1 3 5]


In [8]:
data2D = np.array([[1, 2], [3, 4], [5, 6]])
print("data2D[1, 1]:", data2D[1, 1])
print("data2D[0:2, 0]:", data2D[0:2, 0])

data2D[1, 1]: 4
data2D[0:2, 0]: [1 3]


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [10]:
print("a + b:", a + b)
print("a * b:", a * b)
print("a ** 2:", a ** 2)
print("np.sqrt(a):", np.sqrt(a))
print("np.exp(a):", np.exp(a))
print("np.mean(a):", np.mean(a))

a + b: [5 7 9]
a * b: [ 4 10 18]
a ** 2: [1 4 9]
np.sqrt(a): [1.         1.41421356 1.73205081]
np.exp(a): [ 2.71828183  7.3890561  20.08553692]
np.mean(a): 2.0


In [11]:
data = np.array([1.0, 2.0])
print("data * 2.0:", data * 2.0)

data * 2.0: [2. 4.]


In [12]:
ones = np.ones((2, 3))
print("ones:\n", ones)

ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
data = np.array([[1.0], [2.0]])
print("data + ones:\n", data + ones)

data + ones:
 [[2. 2. 2.]
 [3. 3. 3.]]


In [14]:
data = np.array([[1, 2], [3, 4]])
print("data.sum():", data.sum())
print("data.max():", data.max())
print("data.min():", data.min())
print("data.sum(axis=0):", data.sum(axis=0))
print("data.sum(axis=1):", data.sum(axis=1))

data.sum(): 10
data.max(): 4
data.min(): 1
data.sum(axis=0): [4 6]
data.sum(axis=1): [3 7]


In [15]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print("Original shape:", data.shape)

Original shape: (3, 2)


In [16]:
reshaped = data.reshape(2, 3)
print("Reshaped to (2,3):\n", reshaped)

Reshaped to (2,3):
 [[1 2 3]
 [4 5 6]]


In [17]:
flattened = data.flatten()
print("Flattened:\n", flattened)

Flattened:
 [1 2 3 4 5 6]


In [18]:
raveled = data.ravel()
print("Raveled (view):\n", raveled)

Raveled (view):
 [1 2 3 4 5 6]
